<?php

/**
 * This is the model base class for the table "ProductReturn".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "ProductReturn".
 *
 * Columns in table "ProductReturn" available as properties of the model,
 * followed by relations of table "ProductReturn" available as properties of the model.
 *
 * @property string $ReturnNo
 * @property string $SaleId
 * @property string $CustomerId
 * @property string $ReturnDate
 * @property string $Total
 * @property string $Vat
 * @property string $Status
 * @property string $UpdateAt
 *
 * @property ReturnDetail[] $returnDetails
 */
abstract class BaseProductReturn extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'ProductReturn';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'ProductReturn|ProductReturns', $n);
	}

	public static function representingColumn() {
		return 'ReturnNo';
	}

	public function rules() {
		return array(
			array('ReturnNo, SaleId, CustomerId, Status', 'length', 'max'=>255),
			array('Total, Vat', 'length', 'max'=>20),
			array('ReturnDate, UpdateAt', 'safe'),
			array('ReturnNo, SaleId, CustomerId, ReturnDate, Total, Vat, Status, UpdateAt', 'default', 'setOnEmpty' => true, 'value' => null),
			array('ReturnNo, SaleId, CustomerId, ReturnDate, Total, Vat, Status, UpdateAt', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'returnDetails' => array(self::HAS_MANY, 'ReturnDetail', 'ReturnNo'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'ReturnNo' => Yii::t('app', 'Return No'),
			'SaleId' => Yii::t('app', 'Sale'),
			'CustomerId' => Yii::t('app', 'Customer'),
			'ReturnDate' => Yii::t('app', 'Return Date'),
			'Total' => Yii::t('app', 'Total'),
			'Vat' => Yii::t('app', 'Vat'),
			'Status' => Yii::t('app', 'Status'),
			'UpdateAt' => Yii::t('app', 'Update At'),
			'returnDetails' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('ReturnNo', $this->ReturnNo, true);
		$criteria->compare('SaleId', $this->SaleId, true);
		$criteria->compare('CustomerId', $this->CustomerId, true);
		$criteria->compare('ReturnDate', $this->ReturnDate, true);
		$criteria->compare('Total', $this->Total, true);
		$criteria->compare('Vat', $this->Vat, true);
		$criteria->compare('Status', $this->Status, true);
		$criteria->compare('UpdateAt', $this->UpdateAt, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}