<?php

/**
 * This is the model base class for the table "Trip".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "Trip".
 *
 * Columns in table "Trip" available as properties of the model,
 * and there are no model relations.
 *
 * @property integer $TripId
 * @property string $TripName
 *
 */
abstract class BaseTrip extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'Trip';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'Trip|Trips', $n);
	}

	public static function representingColumn() {
		return 'TripName';
	}

	public function rules() {
		return array(
			array('TripName', 'required'),
			array('TripName', 'length', 'max'=>255),
			array('TripId, TripName', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'TripId' => Yii::t('app', 'Trip'),
			'TripName' => Yii::t('app', 'Trip Name'),
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('TripId', $this->TripId);
		$criteria->compare('TripName', $this->TripName, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}