<?php

/**
 * This is the model base class for the table "PaymentType".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "PaymentType".
 *
 * Columns in table "PaymentType" available as properties of the model,
 * and there are no model relations.
 *
 * @property string $PaymentType
 * @property string $UpdateAt
 *
 */
abstract class BasePaymentType extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'PaymentType';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'PaymentType|PaymentTypes', $n);
	}

	public static function representingColumn() {
		return 'PaymentType';
	}

	public function rules() {
		return array(
			array('PaymentType', 'required'),
			array('PaymentType', 'length', 'max'=>255),
			array('UpdateAt', 'safe'),
			array('UpdateAt', 'default', 'setOnEmpty' => true, 'value' => null),
			array('PaymentType, UpdateAt', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'PaymentType' => Yii::t('app', 'Payment Type'),
			'UpdateAt' => Yii::t('app', 'Update At'),
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('PaymentType', $this->PaymentType, true);
		$criteria->compare('UpdateAt', $this->UpdateAt, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}