<?php

/**
 * This is the model base class for the table "GrpLevel2".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "GrpLevel2".
 *
 * Columns in table "GrpLevel2" available as properties of the model,
 * and there are no model relations.
 *
 * @property string $GrpLevel1Id
 * @property string $GrpLevel2Id
 * @property string $GrpLevel2Name
 * @property string $UpdateAt
 *
 */
abstract class BaseGrpLevel2 extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'GrpLevel2';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'GrpLevel2|GrpLevel2s', $n);
	}

	public static function representingColumn() {
		return 'GrpLevel1Id';
	}

	public function rules() {
		return array(
			array('GrpLevel1Id, GrpLevel2Name', 'required'),
			array('GrpLevel1Id, GrpLevel2Id, GrpLevel2Name', 'length', 'max'=>255),
			array('UpdateAt', 'safe'),
			array('GrpLevel2Id, UpdateAt', 'default', 'setOnEmpty' => true, 'value' => null),
			array('GrpLevel1Id, GrpLevel2Id, GrpLevel2Name, UpdateAt', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'GrpLevel1Id' => Yii::t('app', 'Grp Level1'),
			'GrpLevel2Id' => Yii::t('app', 'Grp Level2'),
			'GrpLevel2Name' => Yii::t('app', 'Grp Level2 Name'),
			'UpdateAt' => Yii::t('app', 'Update At'),
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('GrpLevel1Id', $this->GrpLevel1Id, true);
		$criteria->compare('GrpLevel2Id', $this->GrpLevel2Id, true);
		$criteria->compare('GrpLevel2Name', $this->GrpLevel2Name, true);
		$criteria->compare('UpdateAt', $this->UpdateAt, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}