<?php

/**
 * This is the model base class for the table "CustomerTitle".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "CustomerTitle".
 *
 * Columns in table "CustomerTitle" available as properties of the model,
 * and there are no model relations.
 *
 * @property string $CustomerTitle
 * @property string $UpdateAt
 *
 */
abstract class BaseCustomerTitle extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'CustomerTitle';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'CustomerTitle|CustomerTitles', $n);
	}

	public static function representingColumn() {
		return 'CustomerTitle';
	}

	public function rules() {
		return array(
			array('CustomerTitle', 'required'),
			array('CustomerTitle', 'length', 'max'=>255),
			array('UpdateAt', 'safe'),
			array('UpdateAt', 'default', 'setOnEmpty' => true, 'value' => null),
			array('CustomerTitle, UpdateAt', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'CustomerTitle' => Yii::t('app', 'Customer Title'),
			'UpdateAt' => Yii::t('app', 'Update At'),
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('CustomerTitle', $this->CustomerTitle, true);
		$criteria->compare('UpdateAt', $this->UpdateAt, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}