<?php

/**
 * This is the model base class for the table "StockCheckList".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "StockCheckList".
 *
 * Columns in table "StockCheckList" available as properties of the model,
 * and there are no model relations.
 *
 * @property string $SaleId
 * @property string $GrpLevel1Id
 * @property string $GrpLevel2Id
 * @property string $GrpLevel3Id
 * @property string $ProductId
 * @property string $UpdateAt
 *
 */
abstract class BaseStockCheckList extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'StockCheckList';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'StockCheckList|StockCheckLists', $n);
	}

	public static function representingColumn() {
		return 'SaleId';
	}

	public function rules() {
		return array(
			array('SaleId, GrpLevel1Id, GrpLevel2Id, GrpLevel3Id, ProductId', 'length', 'max'=>255),
			array('UpdateAt', 'safe'),
			array('SaleId, GrpLevel1Id, GrpLevel2Id, GrpLevel3Id, ProductId, UpdateAt', 'default', 'setOnEmpty' => true, 'value' => null),
			array('SaleId, GrpLevel1Id, GrpLevel2Id, GrpLevel3Id, ProductId, UpdateAt', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'SaleId' => Yii::t('app', 'Sale'),
			'GrpLevel1Id' => Yii::t('app', 'Grp Level1'),
			'GrpLevel2Id' => Yii::t('app', 'Grp Level2'),
			'GrpLevel3Id' => Yii::t('app', 'Grp Level3'),
			'ProductId' => Yii::t('app', 'Product'),
			'UpdateAt' => Yii::t('app', 'Update At'),
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('SaleId', $this->SaleId, true);
		$criteria->compare('GrpLevel1Id', $this->GrpLevel1Id, true);
		$criteria->compare('GrpLevel2Id', $this->GrpLevel2Id, true);
		$criteria->compare('GrpLevel3Id', $this->GrpLevel3Id, true);
		$criteria->compare('ProductId', $this->ProductId, true);
		$criteria->compare('UpdateAt', $this->UpdateAt, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}