<?php

/**
 * This is the model base class for the table "TargetSale".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "TargetSale".
 *
 * Columns in table "TargetSale" available as properties of the model,
 * and there are no model relations.
 *
 * @property string $SaleId
 * @property string $Level
 * @property string $ProductOrGrpId
 * @property integer $TargetAmount
 * @property integer $TargetQty
 * @property string $TargetPack
 * @property string $UpdateAt
 *
 */
abstract class BaseTargetSale extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'TargetSale';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'TargetSale|TargetSales', $n);
	}

	public static function representingColumn() {
		return 'SaleId';
	}

	public function rules() {
		return array(
			array('SaleId, Level, TargetPack', 'required'),
			array('TargetAmount, TargetQty', 'numerical', 'integerOnly'=>true),
			array('SaleId, Level, ProductOrGrpId, TargetPack', 'length', 'max'=>255),
			array('UpdateAt', 'safe'),
			array('ProductOrGrpId, TargetAmount, TargetQty, UpdateAt', 'default', 'setOnEmpty' => true, 'value' => null),
			array('SaleId, Level, ProductOrGrpId, TargetAmount, TargetQty, TargetPack, UpdateAt', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'SaleId' => Yii::t('app', 'Sale'),
			'Level' => Yii::t('app', 'Level'),
			'ProductOrGrpId' => Yii::t('app', 'Product Or Grp'),
			'TargetAmount' => Yii::t('app', 'Target Amount'),
			'TargetQty' => Yii::t('app', 'Target Qty'),
			'TargetPack' => Yii::t('app', 'Target Pack'),
			'UpdateAt' => Yii::t('app', 'Update At'),
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('SaleId', $this->SaleId, true);
		$criteria->compare('Level', $this->Level, true);
		$criteria->compare('ProductOrGrpId', $this->ProductOrGrpId, true);
		$criteria->compare('TargetAmount', $this->TargetAmount);
		$criteria->compare('TargetQty', $this->TargetQty);
		$criteria->compare('TargetPack', $this->TargetPack, true);
		$criteria->compare('UpdateAt', $this->UpdateAt, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}