<?php

/**
 * This is the model base class for the table "GrpLevel1".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "GrpLevel1".
 *
 * Columns in table "GrpLevel1" available as properties of the model,
 * and there are no model relations.
 *
 * @property string $GrpLevel1Id
 * @property string $GrpLevel1Name
 * @property string $UpdateAt
 *
 */
abstract class BaseGrpLevel1 extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'GrpLevel1';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'GrpLevel1|GrpLevel1s', $n);
	}

	public static function representingColumn() {
		return 'GrpLevel1Name';
	}

	public function rules() {
		return array(
			array('GrpLevel1Name', 'required'),
			array('GrpLevel1Id, GrpLevel1Name', 'length', 'max'=>255),
			array('UpdateAt', 'safe'),
			array('GrpLevel1Id, UpdateAt', 'default', 'setOnEmpty' => true, 'value' => null),
			array('GrpLevel1Id, GrpLevel1Name, UpdateAt', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'GrpLevel1Id' => Yii::t('app', 'Grp Level1'),
			'GrpLevel1Name' => Yii::t('app', 'Grp Level1 Name'),
			'UpdateAt' => Yii::t('app', 'Update At'),
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('GrpLevel1Id', $this->GrpLevel1Id, true);
		$criteria->compare('GrpLevel1Name', $this->GrpLevel1Name, true);
		$criteria->compare('UpdateAt', $this->UpdateAt, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}