<?php

/**
 * This is the model base class for the table "Config".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "Config".
 *
 * Columns in table "Config" available as properties of the model,
 * and there are no model relations.
 *
 * @property integer $id
 * @property integer $DayToClear
 * @property string $VatPercent
 * @property string $Vat
 * @property string $OverStock
 * @property integer $ExchangeDiff
 * @property string $ExchangePaymentMethod
 * @property string $UpdateAt
 *
 */
abstract class BaseConfig extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'Config';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'Config|Configs', $n);
	}

	public static function representingColumn() {
		return 'VatPercent';
	}

	public function rules() {
		return array(
			array('DayToClear, VatPercent, Vat, OverStock, ExchangeDiff', 'required'),
			array('DayToClear, ExchangeDiff', 'numerical', 'integerOnly'=>true),
			array('VatPercent', 'length', 'max'=>10),
			array('Vat, ExchangePaymentMethod', 'length', 'max'=>255),
			array('OverStock', 'length', 'max'=>1),
			array('UpdateAt', 'safe'),
			array('ExchangePaymentMethod, UpdateAt', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id, DayToClear, VatPercent, Vat, OverStock, ExchangeDiff, ExchangePaymentMethod, UpdateAt', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'DayToClear' => Yii::t('app', 'Day To Clear'),
			'VatPercent' => Yii::t('app', 'Vat Percent'),
			'Vat' => Yii::t('app', 'Vat'),
			'OverStock' => Yii::t('app', 'Over Stock'),
			'ExchangeDiff' => Yii::t('app', 'Exchange Diff'),
			'ExchangePaymentMethod' => Yii::t('app', 'Exchange Payment Method'),
			'UpdateAt' => Yii::t('app', 'Update At'),
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id);
		$criteria->compare('DayToClear', $this->DayToClear);
		$criteria->compare('VatPercent', $this->VatPercent, true);
		$criteria->compare('Vat', $this->Vat, true);
		$criteria->compare('OverStock', $this->OverStock, true);
		$criteria->compare('ExchangeDiff', $this->ExchangeDiff);
		$criteria->compare('ExchangePaymentMethod', $this->ExchangePaymentMethod, true);
		$criteria->compare('UpdateAt', $this->UpdateAt, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}