<?php

/**
 * This is the model base class for the table "StockStartList".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "StockStartList".
 *
 * Columns in table "StockStartList" available as properties of the model,
 * and there are no model relations.
 *
 * @property string $SaleId
 * @property string $ProductId
 * @property integer $QtyLevel1
 * @property integer $QtyLevel2
 * @property integer $QtyLevel3
 * @property integer $QtyLevel4
 * @property string $UpdateAt
 *
 */
abstract class BaseStockStartList extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'StockStartList';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'StockStartList|StockStartLists', $n);
	}

	public static function representingColumn() {
		return 'SaleId';
	}

	public function rules() {
		return array(
			array('QtyLevel1, QtyLevel2, QtyLevel3, QtyLevel4', 'numerical', 'integerOnly'=>true),
			array('SaleId, ProductId', 'length', 'max'=>255),
			array('UpdateAt', 'safe'),
			array('SaleId, ProductId, QtyLevel1, QtyLevel2, QtyLevel3, QtyLevel4, UpdateAt', 'default', 'setOnEmpty' => true, 'value' => null),
			array('SaleId, ProductId, QtyLevel1, QtyLevel2, QtyLevel3, QtyLevel4, UpdateAt', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'SaleId' => Yii::t('app', 'Sale'),
			'ProductId' => Yii::t('app', 'Product'),
			'QtyLevel1' => Yii::t('app', 'Qty Level1'),
			'QtyLevel2' => Yii::t('app', 'Qty Level2'),
			'QtyLevel3' => Yii::t('app', 'Qty Level3'),
			'QtyLevel4' => Yii::t('app', 'Qty Level4'),
			'UpdateAt' => Yii::t('app', 'Update At'),
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('SaleId', $this->SaleId, true);
		$criteria->compare('ProductId', $this->ProductId, true);
		$criteria->compare('QtyLevel1', $this->QtyLevel1);
		$criteria->compare('QtyLevel2', $this->QtyLevel2);
		$criteria->compare('QtyLevel3', $this->QtyLevel3);
		$criteria->compare('QtyLevel4', $this->QtyLevel4);
		$criteria->compare('UpdateAt', $this->UpdateAt, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}