<?php

/**
 * This is the model base class for the table "MoneyTransfer".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "MoneyTransfer".
 *
 * Columns in table "MoneyTransfer" available as properties of the model,
 * and there are no model relations.
 *
 * @property string $SaleId
 * @property string $TransferDate
 * @property string $StartDate
 * @property string $EndDate
 * @property string $Amount
 * @property string $Bank
 * @property string $Branch
 * @property string $AccountNo
 * @property string $Status
 * @property string $UpdateAt
 *
 */
abstract class BaseMoneyTransfer extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'MoneyTransfer';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'MoneyTransfer|MoneyTransfers', $n);
	}

	public static function representingColumn() {
		return 'SaleId';
	}

	public function rules() {
		return array(
			array('SaleId, Bank, Branch, AccountNo, Status', 'length', 'max'=>255),
			array('Amount', 'length', 'max'=>20),
			array('TransferDate, StartDate, UpdateAt', 'safe'),
			array('SaleId, TransferDate, StartDate, EndDate, Amount, Bank, Branch, AccountNo, Status, UpdateAt', 'default', 'setOnEmpty' => true, 'value' => null),
			array('SaleId, TransferDate, StartDate, EndDate, Amount, Bank, Branch, AccountNo, Status, UpdateAt', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'SaleId' => Yii::t('app', 'Sale'),
			'TransferDate' => Yii::t('app', 'Transfer Date'),
			'StartDate' => Yii::t('app', 'Start Date'),
			'EndDate' => Yii::t('app', 'End Date'),
			'Amount' => Yii::t('app', 'Amount'),
			'Bank' => Yii::t('app', 'Bank'),
			'Branch' => Yii::t('app', 'Branch'),
			'AccountNo' => Yii::t('app', 'Account No'),
			'Status' => Yii::t('app', 'Status'),
			'UpdateAt' => Yii::t('app', 'Update At'),
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('SaleId', $this->SaleId, true);
		$criteria->compare('TransferDate', $this->TransferDate, true);
		$criteria->compare('StartDate', $this->StartDate, true);
		$criteria->compare('EndDate', $this->EndDate, true);
		$criteria->compare('Amount', $this->Amount, true);
		$criteria->compare('Bank', $this->Bank, true);
		$criteria->compare('Branch', $this->Branch, true);
		$criteria->compare('AccountNo', $this->AccountNo, true);
		$criteria->compare('Status', $this->Status, true);
		$criteria->compare('UpdateAt', $this->UpdateAt, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}