<?php

/**
 * This is the model base class for the table "GrpLevel3".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "GrpLevel3".
 *
 * Columns in table "GrpLevel3" available as properties of the model,
 * and there are no model relations.
 *
 * @property string $GrpLevel2Id
 * @property string $GrpLevel3Id
 * @property string $GrpLevel3Name
 * @property string $UpdateAt
 *
 */
abstract class BaseGrpLevel3 extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'GrpLevel3';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'GrpLevel3|GrpLevel3s', $n);
	}

	public static function representingColumn() {
		return 'GrpLevel2Id';
	}

	public function rules() {
		return array(
			array('GrpLevel2Id, GrpLevel3Name', 'required'),
			array('GrpLevel2Id, GrpLevel3Id, GrpLevel3Name', 'length', 'max'=>255),
			array('UpdateAt', 'safe'),
			array('GrpLevel3Id, UpdateAt', 'default', 'setOnEmpty' => true, 'value' => null),
			array('GrpLevel2Id, GrpLevel3Id, GrpLevel3Name, UpdateAt', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'GrpLevel2Id' => Yii::t('app', 'Grp Level2'),
			'GrpLevel3Id' => Yii::t('app', 'Grp Level3'),
			'GrpLevel3Name' => Yii::t('app', 'Grp Level3 Name'),
			'UpdateAt' => Yii::t('app', 'Update At'),
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('GrpLevel2Id', $this->GrpLevel2Id, true);
		$criteria->compare('GrpLevel3Id', $this->GrpLevel3Id, true);
		$criteria->compare('GrpLevel3Name', $this->GrpLevel3Name, true);
		$criteria->compare('UpdateAt', $this->UpdateAt, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}