<?php

/**
 * This is the model base class for the table "FreeGrp".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "FreeGrp".
 *
 * Columns in table "FreeGrp" available as properties of the model,
 * and there are no model relations.
 *
 * @property string $FreeGrpId
 * @property string $ProductId
 * @property string $FreePack
 * @property string $UpdateAt
 *
 */
abstract class BaseFreeGrp extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'FreeGrp';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'FreeGrp|FreeGrps', $n);
	}

	public static function representingColumn() {
		return 'FreePack';
	}

	public function rules() {
		return array(
			array('FreeGrpId, ProductId, FreePack', 'required'),
			array('FreeGrpId, ProductId, FreePack', 'length', 'max'=>255),
			array('UpdateAt', 'safe'),
			array('UpdateAt', 'default', 'setOnEmpty' => true, 'value' => null),
			array('FreeGrpId, ProductId, FreePack, UpdateAt', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'FreeGrpId' => Yii::t('app', 'Free Grp'),
			'ProductId' => Yii::t('app', 'Product'),
			'FreePack' => Yii::t('app', 'Free Pack'),
			'UpdateAt' => Yii::t('app', 'Update At'),
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('FreeGrpId', $this->FreeGrpId, true);
		$criteria->compare('ProductId', $this->ProductId, true);
		$criteria->compare('FreePack', $this->FreePack, true);
		$criteria->compare('UpdateAt', $this->UpdateAt, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}