<?php

/**
 * This is the model base class for the table "StockDeliver".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "StockDeliver".
 *
 * Columns in table "StockDeliver" available as properties of the model,
 * followed by relations of table "StockDeliver" available as properties of the model.
 *
 * @property string $RequestNo
 * @property string $DeliverNo
 * @property string $SaleId
 * @property string $WarehouseId
 * @property string $WarehouseName
 * @property string $WarehouseType
 * @property string $DeliverDate
 * @property string $Total
 * @property string $Status
 * @property string $UpdateAt
 *
 * @property DeliverDetail[] $deliverDetails
 */
abstract class BaseStockDeliver extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'StockDeliver';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'StockDeliver|StockDelivers', $n);
	}

	public static function representingColumn() {
		return 'DeliverNo';
	}

	public function rules() {
		return array(
			array('RequestNo, DeliverNo, SaleId, WarehouseId, WarehouseName, WarehouseType, Status', 'length', 'max'=>255),
			array('Total', 'length', 'max'=>10),
			array('DeliverDate, UpdateAt', 'safe'),
			array('RequestNo, DeliverNo, SaleId, WarehouseId, WarehouseName, WarehouseType, DeliverDate, Total, Status, UpdateAt', 'default', 'setOnEmpty' => true, 'value' => null),
			array('RequestNo, DeliverNo, SaleId, WarehouseId, WarehouseName, WarehouseType, DeliverDate, Total, Status, UpdateAt', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'deliverDetails' => array(self::HAS_MANY, 'DeliverDetail', 'DeliverNo'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'RequestNo' => Yii::t('app', 'Request No'),
			'DeliverNo' => Yii::t('app', 'Deliver No'),
			'SaleId' => Yii::t('app', 'Sale'),
			'WarehouseId' => Yii::t('app', 'Warehouse'),
			'WarehouseName' => Yii::t('app', 'Warehouse Name'),
			'WarehouseType' => Yii::t('app', 'Warehouse Type'),
			'DeliverDate' => Yii::t('app', 'Deliver Date'),
			'Total' => Yii::t('app', 'Total'),
			'Status' => Yii::t('app', 'Status'),
			'UpdateAt' => Yii::t('app', 'Update At'),
			'deliverDetails' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('RequestNo', $this->RequestNo, true);
		$criteria->compare('DeliverNo', $this->DeliverNo, true);
		$criteria->compare('SaleId', $this->SaleId, true);
		$criteria->compare('WarehouseId', $this->WarehouseId, true);
		$criteria->compare('WarehouseName', $this->WarehouseName, true);
		$criteria->compare('WarehouseType', $this->WarehouseType, true);
		$criteria->compare('DeliverDate', $this->DeliverDate, true);
		$criteria->compare('Total', $this->Total, true);
		$criteria->compare('Status', $this->Status, true);
		$criteria->compare('UpdateAt', $this->UpdateAt, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}