<?php

/**
 * This is the model base class for the table "StockStartList".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "StockStartList".
 *
 * Columns in table "StockStartList" available as properties of the model,
 * and there are no model relations.
 *
 * @property string $SaleId
 * @property string $ProductId
 * @property integer $Level
 * @property integer $Qty
 * @property string $UpdateAt
 *
 */
abstract class BaseStockStartList extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'StockStartList';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'StockStartList|StockStartLists', $n);
	}

	public static function representingColumn() {
		return 'SaleId';
	}

	public function rules() {
		return array(
			array('Level, Qty', 'numerical', 'integerOnly'=>true),
			array('SaleId, ProductId', 'length', 'max'=>255),
			array('UpdateAt', 'safe'),
			array('SaleId, ProductId, Level, Qty, UpdateAt', 'default', 'setOnEmpty' => true, 'value' => null),
			array('SaleId, ProductId, Level, Qty, UpdateAt', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'SaleId' => Yii::t('app', 'Sale'),
			'ProductId' => Yii::t('app', 'Product'),
			'Level' => Yii::t('app', 'Level'),
			'Qty' => Yii::t('app', 'Qty'),
			'UpdateAt' => Yii::t('app', 'Update At'),
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('SaleId', $this->SaleId, true);
		$criteria->compare('ProductId', $this->ProductId, true);
		$criteria->compare('Level', $this->Level);
		$criteria->compare('Qty', $this->Qty);
		$criteria->compare('UpdateAt', $this->UpdateAt, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}