<?php

/**
 * This is the model base class for the table "ProductGrp".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "ProductGrp".
 *
 * Columns in table "ProductGrp" available as properties of the model,
 * and there are no model relations.
 *
 * @property string $ProductGrpId
 * @property string $ProductId
 * @property string $UpdateAt
 *
 */
abstract class BaseProductGrp extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'ProductGrp';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'ProductGrp|ProductGrps', $n);
	}

	public static function representingColumn() {
		return 'ProductGrpId';
	}

	public function rules() {
		return array(
			array('ProductGrpId, ProductId', 'required'),
			array('ProductGrpId, ProductId', 'length', 'max'=>255),
			array('UpdateAt', 'safe'),
			array('UpdateAt', 'default', 'setOnEmpty' => true, 'value' => null),
			array('ProductGrpId, ProductId, UpdateAt', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'ProductGrpId' => Yii::t('app', 'Product Grp'),
			'ProductId' => Yii::t('app', 'Product'),
			'UpdateAt' => Yii::t('app', 'Update At'),
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('ProductGrpId', $this->ProductGrpId, true);
		$criteria->compare('ProductId', $this->ProductId, true);
		$criteria->compare('UpdateAt', $this->UpdateAt, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}