<?php

/**
 * This is the model base class for the table "FreeDetail".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "FreeDetail".
 *
 * Columns in table "FreeDetail" available as properties of the model,
 * followed by relations of table "FreeDetail" available as properties of the model.
 *
 * @property string $OrderNo
 * @property string $PromotionId
 * @property string $FreeProductId
 * @property string $FreePack
 * @property string $FreePrice
 * @property integer $FreeQty
 * @property string $UpdateAt
 *
 * @property ProductOrder $orderNo
 */
abstract class BaseFreeDetail extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'FreeDetail';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'FreeDetail|FreeDetails', $n);
	}

	public static function representingColumn() {
		return 'PromotionId';
	}

	public function rules() {
		return array(
			array('FreeQty', 'numerical', 'integerOnly'=>true),
			array('OrderNo, PromotionId, FreeProductId, FreePack', 'length', 'max'=>255),
			array('FreePrice', 'length', 'max'=>10),
			array('UpdateAt', 'safe'),
			array('OrderNo, PromotionId, FreeProductId, FreePack, FreePrice, FreeQty, UpdateAt', 'default', 'setOnEmpty' => true, 'value' => null),
			array('OrderNo, PromotionId, FreeProductId, FreePack, FreePrice, FreeQty, UpdateAt', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'orderNo' => array(self::BELONGS_TO, 'ProductOrder', 'OrderNo'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'OrderNo' => null,
			'PromotionId' => Yii::t('app', 'Promotion'),
			'FreeProductId' => Yii::t('app', 'Free Product'),
			'FreePack' => Yii::t('app', 'Free Pack'),
			'FreePrice' => Yii::t('app', 'Free Price'),
			'FreeQty' => Yii::t('app', 'Free Qty'),
			'UpdateAt' => Yii::t('app', 'Update At'),
			'orderNo' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('OrderNo', $this->OrderNo);
		$criteria->compare('PromotionId', $this->PromotionId, true);
		$criteria->compare('FreeProductId', $this->FreeProductId, true);
		$criteria->compare('FreePack', $this->FreePack, true);
		$criteria->compare('FreePrice', $this->FreePrice, true);
		$criteria->compare('FreeQty', $this->FreeQty);
		$criteria->compare('UpdateAt', $this->UpdateAt, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}