<?php

/**
 * This is the model base class for the table "Payment".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "Payment".
 *
 * Columns in table "Payment" available as properties of the model,
 * and there are no model relations.
 *
 * @property string $CollectionNo
 * @property string $PaymentId
 * @property string $PaymentType
 * @property string $PaidAmount
 * @property string $DocNo
 * @property string $DocDate
 * @property string $Bank
 * @property string $Branch
 * @property string $AccountNo
 * @property string $UpdateAt
 *
 */
abstract class BasePayment extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'Payment';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'Payment|Payments', $n);
	}

	public static function representingColumn() {
		return 'PaymentId';
	}

	public function rules() {
		return array(
			array('CollectionNo, PaymentId, PaymentType, DocNo, DocDate, Bank, Branch, AccountNo', 'length', 'max'=>255),
			array('PaidAmount', 'length', 'max'=>20),
			array('UpdateAt', 'safe'),
			array('CollectionNo, PaymentId, PaymentType, PaidAmount, DocNo, DocDate, Bank, Branch, AccountNo, UpdateAt', 'default', 'setOnEmpty' => true, 'value' => null),
			array('CollectionNo, PaymentId, PaymentType, PaidAmount, DocNo, DocDate, Bank, Branch, AccountNo, UpdateAt', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'CollectionNo' => Yii::t('app', 'Collection No'),
			'PaymentId' => Yii::t('app', 'Payment'),
			'PaymentType' => Yii::t('app', 'Payment Type'),
			'PaidAmount' => Yii::t('app', 'Paid Amount'),
			'DocNo' => Yii::t('app', 'Doc No'),
			'DocDate' => Yii::t('app', 'Doc Date'),
			'Bank' => Yii::t('app', 'Bank'),
			'Branch' => Yii::t('app', 'Branch'),
			'AccountNo' => Yii::t('app', 'Account No'),
			'UpdateAt' => Yii::t('app', 'Update At'),
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('CollectionNo', $this->CollectionNo, true);
		$criteria->compare('PaymentId', $this->PaymentId, true);
		$criteria->compare('PaymentType', $this->PaymentType, true);
		$criteria->compare('PaidAmount', $this->PaidAmount, true);
		$criteria->compare('DocNo', $this->DocNo, true);
		$criteria->compare('DocDate', $this->DocDate, true);
		$criteria->compare('Bank', $this->Bank, true);
		$criteria->compare('Branch', $this->Branch, true);
		$criteria->compare('AccountNo', $this->AccountNo, true);
		$criteria->compare('UpdateAt', $this->UpdateAt, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}